api:
  anthropic:
    base_url: https://api.anthropic.com
    models:
    - claude-3-sonnet-20240229
    - claude-3-opus-20240229
    - claude-3-haiku-20240307
  azure:
    endpoint: null
    region: eastus
  deepseek:
    base_url: https://api.deepseek.com/v1
    models:
    - deepseek-chat
    - deepseek-coder
  google:
    location: global
    project_id: null
  ollama:
    base_url: http://localhost:11434/v1
    models:
    - llama2
    - llama2:13b
    - llama2:70b
    - codellama
    - codellama:13b
    - mistral
    - mixtral
    - qwen
    - gemma
  openai:
    base_url: https://api.openai.com/v1
    models:
    - gpt-3.5-turbo
    - gpt-4
    - gpt-4-turbo-preview
logging:
  backup_count: 5
  console_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  enable_colors: true
  enable_console: true
  enable_file: true
  file: logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size: 10MB
output:
  create_backup: true
  default_dir: ./output
  filename_template: '{original_name}_{lang}_{format}'
  overwrite_existing: false
subtitle:
  ass_style:
    back_color: '&H80000000'
    font_name: Arial
    font_size: 20
    outline_color: '&H00000000'
    primary_color: '&H00FFFFFF'
    secondary_color: '&H000000FF'
  auto_detect_language: true
  encoding: utf-8
  formats:
  - srt
  - vtt
  - ass
  max_chars_per_line: 50
  max_lines: 2
  merge_short_segments: true
  min_segment_duration: 1.0
  sync_tolerance: 0.1
translation:
  batch_size: 10
  max_tokens: 2000
  model: gpt-3.5-turbo
  output_format: bilingual
  provider: openai
  retry_count: 3
  target_language: zh-CN
  temperature: 0.3
  timeout: 30
ui:
  auto_save_config: true
  language: zh_CN
  last_used_dir: /mnt/diskd/media/tv
  remember_last_dir: true
  show_progress_details: true
  theme: arc
  window_size: 1200x800
video:
  audio_format: wav
  audio_sample_rate: 16000
  extract_audio: false
  ffmpeg_path: ffmpeg
  supported_formats:
  - .mp4
  - .avi
  - .mkv
  - .mov
  - .wmv
  - .flv
  - .webm
  - .m4v
